/*
 * White Fox Lana Api
 *
 * Lana Apis
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets ActionType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ActionType
        {
            /// <summary>
            /// Enum InsertedEnum for inserted
            /// </summary>
            [EnumMember(Value = "inserted")]
            InsertedEnum = 0,
            /// <summary>
            /// Enum UpdatedEnum for updated
            /// </summary>
            [EnumMember(Value = "updated")]
            UpdatedEnum = 1,
            /// <summary>
            /// Enum DeletedEnum for deleted
            /// </summary>
            [EnumMember(Value = "deleted")]
            DeletedEnum = 2,
            /// <summary>
            /// Enum ActivatedEnum for activated
            /// </summary>
            [EnumMember(Value = "activated")]
            ActivatedEnum = 3,
            /// <summary>
            /// Enum DeativatedEnum for deativated
            /// </summary>
            [EnumMember(Value = "deativated")]
            DeativatedEnum = 4,
            /// <summary>
            /// Enum ClosedEnum for closed
            /// </summary>
            [EnumMember(Value = "closed")]
            ClosedEnum = 5,
            /// <summary>
            /// Enum OpenedEnum for opened
            /// </summary>
            [EnumMember(Value = "opened")]
            OpenedEnum = 6        }
}
