/*
 * Onyx Domain API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets HttpStatusCode
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum HttpStatusCode
        {
            /// <summary>
            /// Enum NUMBER_100 for 100
            /// </summary>
            [EnumMember(Value = "100")]
            NUMBER_100 = 0,
            /// <summary>
            /// Enum NUMBER_101 for 101
            /// </summary>
            [EnumMember(Value = "101")]
            NUMBER_101 = 1,
            /// <summary>
            /// Enum NUMBER_102 for 102
            /// </summary>
            [EnumMember(Value = "102")]
            NUMBER_102 = 2,
            /// <summary>
            /// Enum NUMBER_103 for 103
            /// </summary>
            [EnumMember(Value = "103")]
            NUMBER_103 = 3,
            /// <summary>
            /// Enum NUMBER_200 for 200
            /// </summary>
            [EnumMember(Value = "200")]
            NUMBER_200 = 4,
            /// <summary>
            /// Enum NUMBER_201 for 201
            /// </summary>
            [EnumMember(Value = "201")]
            NUMBER_201 = 5,
            /// <summary>
            /// Enum NUMBER_202 for 202
            /// </summary>
            [EnumMember(Value = "202")]
            NUMBER_202 = 6,
            /// <summary>
            /// Enum NUMBER_203 for 203
            /// </summary>
            [EnumMember(Value = "203")]
            NUMBER_203 = 7,
            /// <summary>
            /// Enum NUMBER_204 for 204
            /// </summary>
            [EnumMember(Value = "204")]
            NUMBER_204 = 8,
            /// <summary>
            /// Enum NUMBER_205 for 205
            /// </summary>
            [EnumMember(Value = "205")]
            NUMBER_205 = 9,
            /// <summary>
            /// Enum NUMBER_206 for 206
            /// </summary>
            [EnumMember(Value = "206")]
            NUMBER_206 = 10,
            /// <summary>
            /// Enum NUMBER_207 for 207
            /// </summary>
            [EnumMember(Value = "207")]
            NUMBER_207 = 11,
            /// <summary>
            /// Enum NUMBER_208 for 208
            /// </summary>
            [EnumMember(Value = "208")]
            NUMBER_208 = 12,
            /// <summary>
            /// Enum NUMBER_226 for 226
            /// </summary>
            [EnumMember(Value = "226")]
            NUMBER_226 = 13,
            /// <summary>
            /// Enum NUMBER_300 for 300
            /// </summary>
            [EnumMember(Value = "300")]
            NUMBER_300 = 14,
            /// <summary>
            /// Enum NUMBER_301 for 301
            /// </summary>
            [EnumMember(Value = "301")]
            NUMBER_301 = 15,
            /// <summary>
            /// Enum NUMBER_302 for 302
            /// </summary>
            [EnumMember(Value = "302")]
            NUMBER_302 = 16,
            /// <summary>
            /// Enum NUMBER_303 for 303
            /// </summary>
            [EnumMember(Value = "303")]
            NUMBER_303 = 17,
            /// <summary>
            /// Enum NUMBER_304 for 304
            /// </summary>
            [EnumMember(Value = "304")]
            NUMBER_304 = 18,
            /// <summary>
            /// Enum NUMBER_305 for 305
            /// </summary>
            [EnumMember(Value = "305")]
            NUMBER_305 = 19,
            /// <summary>
            /// Enum NUMBER_306 for 306
            /// </summary>
            [EnumMember(Value = "306")]
            NUMBER_306 = 20,
            /// <summary>
            /// Enum NUMBER_307 for 307
            /// </summary>
            [EnumMember(Value = "307")]
            NUMBER_307 = 21,
            /// <summary>
            /// Enum NUMBER_308 for 308
            /// </summary>
            [EnumMember(Value = "308")]
            NUMBER_308 = 22,
            /// <summary>
            /// Enum NUMBER_400 for 400
            /// </summary>
            [EnumMember(Value = "400")]
            NUMBER_400 = 23,
            /// <summary>
            /// Enum NUMBER_401 for 401
            /// </summary>
            [EnumMember(Value = "401")]
            NUMBER_401 = 24,
            /// <summary>
            /// Enum NUMBER_402 for 402
            /// </summary>
            [EnumMember(Value = "402")]
            NUMBER_402 = 25,
            /// <summary>
            /// Enum NUMBER_403 for 403
            /// </summary>
            [EnumMember(Value = "403")]
            NUMBER_403 = 26,
            /// <summary>
            /// Enum NUMBER_404 for 404
            /// </summary>
            [EnumMember(Value = "404")]
            NUMBER_404 = 27,
            /// <summary>
            /// Enum NUMBER_405 for 405
            /// </summary>
            [EnumMember(Value = "405")]
            NUMBER_405 = 28,
            /// <summary>
            /// Enum NUMBER_406 for 406
            /// </summary>
            [EnumMember(Value = "406")]
            NUMBER_406 = 29,
            /// <summary>
            /// Enum NUMBER_407 for 407
            /// </summary>
            [EnumMember(Value = "407")]
            NUMBER_407 = 30,
            /// <summary>
            /// Enum NUMBER_408 for 408
            /// </summary>
            [EnumMember(Value = "408")]
            NUMBER_408 = 31,
            /// <summary>
            /// Enum NUMBER_409 for 409
            /// </summary>
            [EnumMember(Value = "409")]
            NUMBER_409 = 32,
            /// <summary>
            /// Enum NUMBER_410 for 410
            /// </summary>
            [EnumMember(Value = "410")]
            NUMBER_410 = 33,
            /// <summary>
            /// Enum NUMBER_411 for 411
            /// </summary>
            [EnumMember(Value = "411")]
            NUMBER_411 = 34,
            /// <summary>
            /// Enum NUMBER_412 for 412
            /// </summary>
            [EnumMember(Value = "412")]
            NUMBER_412 = 35,
            /// <summary>
            /// Enum NUMBER_413 for 413
            /// </summary>
            [EnumMember(Value = "413")]
            NUMBER_413 = 36,
            /// <summary>
            /// Enum NUMBER_414 for 414
            /// </summary>
            [EnumMember(Value = "414")]
            NUMBER_414 = 37,
            /// <summary>
            /// Enum NUMBER_415 for 415
            /// </summary>
            [EnumMember(Value = "415")]
            NUMBER_415 = 38,
            /// <summary>
            /// Enum NUMBER_416 for 416
            /// </summary>
            [EnumMember(Value = "416")]
            NUMBER_416 = 39,
            /// <summary>
            /// Enum NUMBER_417 for 417
            /// </summary>
            [EnumMember(Value = "417")]
            NUMBER_417 = 40,
            /// <summary>
            /// Enum NUMBER_421 for 421
            /// </summary>
            [EnumMember(Value = "421")]
            NUMBER_421 = 41,
            /// <summary>
            /// Enum NUMBER_422 for 422
            /// </summary>
            [EnumMember(Value = "422")]
            NUMBER_422 = 42,
            /// <summary>
            /// Enum NUMBER_423 for 423
            /// </summary>
            [EnumMember(Value = "423")]
            NUMBER_423 = 43,
            /// <summary>
            /// Enum NUMBER_424 for 424
            /// </summary>
            [EnumMember(Value = "424")]
            NUMBER_424 = 44,
            /// <summary>
            /// Enum NUMBER_426 for 426
            /// </summary>
            [EnumMember(Value = "426")]
            NUMBER_426 = 45,
            /// <summary>
            /// Enum NUMBER_428 for 428
            /// </summary>
            [EnumMember(Value = "428")]
            NUMBER_428 = 46,
            /// <summary>
            /// Enum NUMBER_429 for 429
            /// </summary>
            [EnumMember(Value = "429")]
            NUMBER_429 = 47,
            /// <summary>
            /// Enum NUMBER_431 for 431
            /// </summary>
            [EnumMember(Value = "431")]
            NUMBER_431 = 48,
            /// <summary>
            /// Enum NUMBER_451 for 451
            /// </summary>
            [EnumMember(Value = "451")]
            NUMBER_451 = 49,
            /// <summary>
            /// Enum NUMBER_500 for 500
            /// </summary>
            [EnumMember(Value = "500")]
            NUMBER_500 = 50,
            /// <summary>
            /// Enum NUMBER_501 for 501
            /// </summary>
            [EnumMember(Value = "501")]
            NUMBER_501 = 51,
            /// <summary>
            /// Enum NUMBER_502 for 502
            /// </summary>
            [EnumMember(Value = "502")]
            NUMBER_502 = 52,
            /// <summary>
            /// Enum NUMBER_503 for 503
            /// </summary>
            [EnumMember(Value = "503")]
            NUMBER_503 = 53,
            /// <summary>
            /// Enum NUMBER_504 for 504
            /// </summary>
            [EnumMember(Value = "504")]
            NUMBER_504 = 54,
            /// <summary>
            /// Enum NUMBER_505 for 505
            /// </summary>
            [EnumMember(Value = "505")]
            NUMBER_505 = 55,
            /// <summary>
            /// Enum NUMBER_506 for 506
            /// </summary>
            [EnumMember(Value = "506")]
            NUMBER_506 = 56,
            /// <summary>
            /// Enum NUMBER_507 for 507
            /// </summary>
            [EnumMember(Value = "507")]
            NUMBER_507 = 57,
            /// <summary>
            /// Enum NUMBER_508 for 508
            /// </summary>
            [EnumMember(Value = "508")]
            NUMBER_508 = 58,
            /// <summary>
            /// Enum NUMBER_510 for 510
            /// </summary>
            [EnumMember(Value = "510")]
            NUMBER_510 = 59,
            /// <summary>
            /// Enum NUMBER_511 for 511
            /// </summary>
            [EnumMember(Value = "511")]
            NUMBER_511 = 60        }
}
