/*
 * White Fox Lana Api
 *
 * Lana Apis
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
        /// <summary>
        /// Gets or Sets NotificationType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NotificationType
        {
            /// <summary>
            /// Enum DashboardUpdatedEnum for dashboardUpdated
            /// </summary>
            [EnumMember(Value = "dashboardUpdated")]
            DashboardUpdatedEnum = 0,
            /// <summary>
            /// Enum UserEffortUpdatedEnum for userEffortUpdated
            /// </summary>
            [EnumMember(Value = "userEffortUpdated")]
            UserEffortUpdatedEnum = 1,
            /// <summary>
            /// Enum TransactionExecutedEnum for transactionExecuted
            /// </summary>
            [EnumMember(Value = "transactionExecuted")]
            TransactionExecutedEnum = 2        }
}
