/*
 * Onyx Domain API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class QueriesApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Queries/FaPricesDate")]
        [ValidateModelState]
        [SwaggerOperation("QueriesFaPricesDatePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Result), description: "Success")]
        public virtual IActionResult QueriesFaPricesDatePost([FromBody]StatementYearRefTickerDateParameterParameter body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Result));
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"message\" : \"message\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Result>(exampleJson)
                        : default(Result);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Queries/FaPricesValue")]
        [ValidateModelState]
        [SwaggerOperation("QueriesFaPricesValuePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Result), description: "Success")]
        public virtual IActionResult QueriesFaPricesValuePost([FromBody]StatementYearRefTickerDateParameterParameter body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Result));
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"message\" : \"message\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Result>(exampleJson)
                        : default(Result);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Queries/FaTarget")]
        [ValidateModelState]
        [SwaggerOperation("QueriesFaTargetPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Result), description: "Success")]
        public virtual IActionResult QueriesFaTargetPost([FromBody]StatementYearRefTickerDateParameterParameter body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Result));
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"message\" : \"message\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Result>(exampleJson)
                        : default(Result);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Queries/MktCap")]
        [ValidateModelState]
        [SwaggerOperation("QueriesMktCapPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Result), description: "Success")]
        public virtual IActionResult QueriesMktCapPost([FromBody]TickerDateUsdParameterParameter body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Result));
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"message\" : \"message\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Result>(exampleJson)
                        : default(Result);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Queries/Nav")]
        [ValidateModelState]
        [SwaggerOperation("QueriesNavPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Result), description: "Success")]
        public virtual IActionResult QueriesNavPost([FromBody]FundDateParameterParameter body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Result));
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"message\" : \"message\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Result>(exampleJson)
                        : default(Result);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Queries/SecurityPrice")]
        [ValidateModelState]
        [SwaggerOperation("QueriesSecurityPricePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Result), description: "Success")]
        public virtual IActionResult QueriesSecurityPricePost([FromBody]TickerDateUsdParameterParameter body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Result));
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"message\" : \"message\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Result>(exampleJson)
                        : default(Result);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Queries/TotalQuantity")]
        [ValidateModelState]
        [SwaggerOperation("QueriesTotalQuantityPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Result), description: "Success")]
        public virtual IActionResult QueriesTotalQuantityPost([FromBody]TickerDateUsdParameterParameter body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Result));
            string exampleJson = null;
            exampleJson = "{\n  \"success\" : true,\n  \"message\" : \"message\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Result>(exampleJson)
                        : default(Result);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
